const data = [
  {
    keyId: 0,
    keyName: "LOGO",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 1,
    keyName: "FN1",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 2,
    keyName: "FN2",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 3,
    keyName: "FN3",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 4,
    keyName: "FN4",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 5,
    keyName: "FN5",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 6,
    keyName: "~",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 7,
    keyName: "1",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 8,
    keyName: "2",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 9,
    keyName: "3",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 10,
    keyName: "4",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 11,
    keyName: "5",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 12,
    keyName: "TAB",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 13,
    keyName: "Q",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 14,
    keyName: "W",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 15,
    keyName: "E",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 16,
    keyName: "R",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 17,
    keyName: "T",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 18,
    keyName: "CAPS",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 19,
    keyName: "A",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 20,
    keyName: "S",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 21,
    keyName: "D",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 22,
    keyName: "F",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 23,
    keyName: "G",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 24,
    keyName: "SHIFT",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 25,
    keyName: "Z",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 26,
    keyName: "X",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 27,
    keyName: "C",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 28,
    keyName: "V",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 29,
    keyName: "B",
    color: "#000000",
    isSelected: false,
  },
  {
    keyId: 30,
    keyName: "SPACE",
    color: "#000000",
    isSelected: false,
  },
];

export default data;
